---
title: "STA330"
output: html_document
date: '2023-03-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##

```{r}
#install.packages("cluster")
#install.packages("factoextra")
#install.packages("psych")
#install.packages("ggplot2")
#install.packages("writexl")
library(psych)
library(cluster)
library(factoextra)
library(ggplot2)
library(dplyr)
library(readxl)
library(writexl)
```
##
```{r}
BABG <- read_excel("~/Downloads/Tokenized.xlsx")
as.numeric(BABG>0)
fun <- function(x)
  {as.numeric(x>0)
}
result_1<-apply(BABG,2,fun)
s <- colsum_1<-colSums(result_1)
keep_col <- which(s>=25)
BABG<-BABG[,keep_col]
#rowSums(BABG)
```


```{r}
# 10 most useful column; length soriting into groups; pretrained setiments [transdfer learning ]
# Determine K - determine the optimal number of clusters using the elbow method
fviz_nbclust(BABG, FUNcluster = kmeans, method = "wss", k.max = 40)

```

``` {r}
k2 <- kmeans(BABG, centers = 15)
center_show<-k2$centers
center_show
# Visualizing clusters
fviz_cluster(k2, data = BABG)
```


```{r}
BABG_std <- scale(BABG)
rownames(BABG_std) <-1:nrow(BABG_std)
BABG_pam <- pam(BABG_std, k = 5)  ## Apply PAM clustering
testing <-BABG_pam$medoids
testing
clusterlabels = BABG_pam$clustering
clusterlabels
hello<-data.frame(clusterlabels)
hello
write.csv(hello, "1stQ.csv")
fviz_cluster(BABG_pam)
#read the responses of the centroids of the clustering. can we give each or any of the clusters any categories? unique things about each of these responses
```



















